/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 28
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_symbol = 1,
  sym_comment = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  sym_integer = 9,
  sym_string = 10,
  anon_sym_true = 11,
  anon_sym_false = 12,
  sym_constructor = 13,
  aux_sym_module_token1 = 14,
  sym_source_file = 15,
  sym__expr = 16,
  sym_call = 17,
  sym_list = 18,
  sym_tuple = 19,
  sym_bool = 20,
  sym_module = 21,
  aux_sym_source_file_repeat1 = 22,
  aux_sym_call_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_symbol] = "symbol",
  [sym_comment] = "comment",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_integer] = "integer",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_constructor] = "constructor",
  [aux_sym_module_token1] = "module_token1",
  [sym_source_file] = "source_file",
  [sym__expr] = "_expr",
  [sym_call] = "call",
  [sym_list] = "list",
  [sym_tuple] = "tuple",
  [sym_bool] = "bool",
  [sym_module] = "module",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_call_repeat1] = "call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_symbol] = sym_symbol,
  [sym_comment] = sym_comment,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_integer] = sym_integer,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_constructor] = sym_constructor,
  [aux_sym_module_token1] = aux_sym_module_token1,
  [sym_source_file] = sym_source_file,
  [sym__expr] = sym__expr,
  [sym_call] = sym_call,
  [sym_list] = sym_list,
  [sym_tuple] = sym_tuple,
  [sym_bool] = sym_bool,
  [sym_module] = sym_module,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_constructor] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_module_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_callee = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_callee] = "callee",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_callee, 1},
  [1] =
    {field_argument, 0},
  [2] =
    {field_argument, 2, .inherited = true},
    {field_callee, 1},
  [4] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 2,
  [10] = 4,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 12,
  [15] = 7,
  [16] = 8,
  [17] = 13,
  [18] = 18,
  [19] = 18,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 20,
  [29] = 27,
  [30] = 26,
  [31] = 25,
  [32] = 21,
  [33] = 33,
  [34] = 22,
  [35] = 23,
  [36] = 24,
  [37] = 37,
  [38] = 37,
  [39] = 39,
};

static const TSCharacterRange sym_symbol_character_set_1[] = {
  {'!', '!'}, {'$', '&'}, {'*', '+'}, {'-', '-'}, {'/', '/'}, {':', ':'}, {'<', '?'}, {'^', '_'},
  {'a', 'z'}, {'~', '~'},
};

static const TSCharacterRange sym_symbol_character_set_2[] = {
  {'!', '!'}, {'$', '&'}, {'*', '+'}, {'-', ':'}, {'<', '?'}, {'A', 'Z'}, {'^', '_'}, {'a', 'z'},
  {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '"', 1,
        '$', 18,
        '(', 7,
        ')', 8,
        '-', 20,
        '0', 13,
        '[', 9,
        ']', 10,
        '{', 11,
        '}', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(2);
      if (set_contains(sym_symbol_character_set_1, 10, lookahead)) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_comment);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_integer);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(21);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_integer);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(21);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_constructor);
      if ((set_contains(sym_symbol_character_set_1, 10, lookahead) ||
          lookahead == '.') &&
          lookahead != '-' &&
          lookahead != '_' &&
          (lookahead < 'a' || 'z' < lookahead)) ADVANCE(21);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_module_token1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '0') ADVANCE(16);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_symbol);
      if (set_contains(sym_symbol_character_set_2, 9, lookahead)) ADVANCE(21);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 't') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_constructor] = ACTIONS(1),
    [aux_sym_module_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(39),
    [sym__expr] = STATE(5),
    [sym_call] = STATE(5),
    [sym_list] = STATE(5),
    [sym_tuple] = STATE(5),
    [sym_bool] = STATE(5),
    [sym_module] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_symbol] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [sym_integer] = ACTIONS(7),
    [sym_string] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_constructor] = ACTIONS(7),
    [aux_sym_module_token1] = ACTIONS(19),
  },
  [STATE(2)] = {
    [sym__expr] = STATE(2),
    [sym_call] = STATE(2),
    [sym_list] = STATE(2),
    [sym_tuple] = STATE(2),
    [sym_bool] = STATE(2),
    [sym_module] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(24),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(30),
    [anon_sym_LBRACE] = ACTIONS(32),
    [anon_sym_RBRACE] = ACTIONS(30),
    [sym_integer] = ACTIONS(21),
    [sym_string] = ACTIONS(35),
    [anon_sym_true] = ACTIONS(38),
    [anon_sym_false] = ACTIONS(38),
    [sym_constructor] = ACTIONS(21),
    [aux_sym_module_token1] = ACTIONS(41),
  },
  [STATE(3)] = {
    [sym__expr] = STATE(33),
    [sym_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_tuple] = STATE(33),
    [sym_bool] = STATE(33),
    [sym_module] = STATE(33),
    [aux_sym_call_repeat1] = STATE(4),
    [sym_symbol] = ACTIONS(44),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_RPAREN] = ACTIONS(48),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_LBRACE] = ACTIONS(52),
    [sym_integer] = ACTIONS(44),
    [sym_string] = ACTIONS(54),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_constructor] = ACTIONS(44),
    [aux_sym_module_token1] = ACTIONS(58),
  },
  [STATE(4)] = {
    [sym__expr] = STATE(33),
    [sym_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_tuple] = STATE(33),
    [sym_bool] = STATE(33),
    [sym_module] = STATE(33),
    [aux_sym_call_repeat1] = STATE(11),
    [sym_symbol] = ACTIONS(44),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_RPAREN] = ACTIONS(60),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_LBRACE] = ACTIONS(52),
    [sym_integer] = ACTIONS(44),
    [sym_string] = ACTIONS(54),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_constructor] = ACTIONS(44),
    [aux_sym_module_token1] = ACTIONS(58),
  },
  [STATE(5)] = {
    [sym__expr] = STATE(9),
    [sym_call] = STATE(9),
    [sym_list] = STATE(9),
    [sym_tuple] = STATE(9),
    [sym_bool] = STATE(9),
    [sym_module] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(62),
    [sym_symbol] = ACTIONS(64),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [sym_integer] = ACTIONS(64),
    [sym_string] = ACTIONS(66),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_constructor] = ACTIONS(64),
    [aux_sym_module_token1] = ACTIONS(19),
  },
  [STATE(6)] = {
    [sym__expr] = STATE(33),
    [sym_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_tuple] = STATE(33),
    [sym_bool] = STATE(33),
    [sym_module] = STATE(33),
    [aux_sym_call_repeat1] = STATE(10),
    [sym_symbol] = ACTIONS(44),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_RPAREN] = ACTIONS(68),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_LBRACE] = ACTIONS(52),
    [sym_integer] = ACTIONS(44),
    [sym_string] = ACTIONS(54),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_constructor] = ACTIONS(44),
    [aux_sym_module_token1] = ACTIONS(58),
  },
  [STATE(7)] = {
    [sym__expr] = STATE(2),
    [sym_call] = STATE(2),
    [sym_list] = STATE(2),
    [sym_tuple] = STATE(2),
    [sym_bool] = STATE(2),
    [sym_module] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(70),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_RBRACK] = ACTIONS(72),
    [anon_sym_LBRACE] = ACTIONS(52),
    [sym_integer] = ACTIONS(70),
    [sym_string] = ACTIONS(74),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_constructor] = ACTIONS(70),
    [aux_sym_module_token1] = ACTIONS(58),
  },
  [STATE(8)] = {
    [sym__expr] = STATE(2),
    [sym_call] = STATE(2),
    [sym_list] = STATE(2),
    [sym_tuple] = STATE(2),
    [sym_bool] = STATE(2),
    [sym_module] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(70),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_LBRACE] = ACTIONS(52),
    [anon_sym_RBRACE] = ACTIONS(76),
    [sym_integer] = ACTIONS(70),
    [sym_string] = ACTIONS(74),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_constructor] = ACTIONS(70),
    [aux_sym_module_token1] = ACTIONS(58),
  },
  [STATE(9)] = {
    [sym__expr] = STATE(9),
    [sym_call] = STATE(9),
    [sym_list] = STATE(9),
    [sym_tuple] = STATE(9),
    [sym_bool] = STATE(9),
    [sym_module] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(30),
    [sym_symbol] = ACTIONS(78),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(81),
    [anon_sym_LBRACK] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(87),
    [sym_integer] = ACTIONS(78),
    [sym_string] = ACTIONS(90),
    [anon_sym_true] = ACTIONS(93),
    [anon_sym_false] = ACTIONS(93),
    [sym_constructor] = ACTIONS(78),
    [aux_sym_module_token1] = ACTIONS(96),
  },
  [STATE(10)] = {
    [sym__expr] = STATE(33),
    [sym_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_tuple] = STATE(33),
    [sym_bool] = STATE(33),
    [sym_module] = STATE(33),
    [aux_sym_call_repeat1] = STATE(11),
    [sym_symbol] = ACTIONS(44),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_RPAREN] = ACTIONS(99),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_LBRACE] = ACTIONS(52),
    [sym_integer] = ACTIONS(44),
    [sym_string] = ACTIONS(54),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_constructor] = ACTIONS(44),
    [aux_sym_module_token1] = ACTIONS(58),
  },
  [STATE(11)] = {
    [sym__expr] = STATE(33),
    [sym_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_tuple] = STATE(33),
    [sym_bool] = STATE(33),
    [sym_module] = STATE(33),
    [aux_sym_call_repeat1] = STATE(11),
    [sym_symbol] = ACTIONS(101),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_RPAREN] = ACTIONS(107),
    [anon_sym_LBRACK] = ACTIONS(109),
    [anon_sym_LBRACE] = ACTIONS(112),
    [sym_integer] = ACTIONS(101),
    [sym_string] = ACTIONS(115),
    [anon_sym_true] = ACTIONS(118),
    [anon_sym_false] = ACTIONS(118),
    [sym_constructor] = ACTIONS(101),
    [aux_sym_module_token1] = ACTIONS(121),
  },
  [STATE(12)] = {
    [sym__expr] = STATE(15),
    [sym_call] = STATE(15),
    [sym_list] = STATE(15),
    [sym_tuple] = STATE(15),
    [sym_bool] = STATE(15),
    [sym_module] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(15),
    [sym_symbol] = ACTIONS(124),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_RBRACK] = ACTIONS(126),
    [anon_sym_LBRACE] = ACTIONS(52),
    [sym_integer] = ACTIONS(124),
    [sym_string] = ACTIONS(128),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_constructor] = ACTIONS(124),
    [aux_sym_module_token1] = ACTIONS(58),
  },
  [STATE(13)] = {
    [sym__expr] = STATE(16),
    [sym_call] = STATE(16),
    [sym_list] = STATE(16),
    [sym_tuple] = STATE(16),
    [sym_bool] = STATE(16),
    [sym_module] = STATE(16),
    [aux_sym_source_file_repeat1] = STATE(16),
    [sym_symbol] = ACTIONS(130),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_LBRACE] = ACTIONS(52),
    [anon_sym_RBRACE] = ACTIONS(132),
    [sym_integer] = ACTIONS(130),
    [sym_string] = ACTIONS(134),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_constructor] = ACTIONS(130),
    [aux_sym_module_token1] = ACTIONS(58),
  },
  [STATE(14)] = {
    [sym__expr] = STATE(7),
    [sym_call] = STATE(7),
    [sym_list] = STATE(7),
    [sym_tuple] = STATE(7),
    [sym_bool] = STATE(7),
    [sym_module] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_symbol] = ACTIONS(136),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_RBRACK] = ACTIONS(138),
    [anon_sym_LBRACE] = ACTIONS(52),
    [sym_integer] = ACTIONS(136),
    [sym_string] = ACTIONS(140),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_constructor] = ACTIONS(136),
    [aux_sym_module_token1] = ACTIONS(58),
  },
  [STATE(15)] = {
    [sym__expr] = STATE(2),
    [sym_call] = STATE(2),
    [sym_list] = STATE(2),
    [sym_tuple] = STATE(2),
    [sym_bool] = STATE(2),
    [sym_module] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(70),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_RBRACK] = ACTIONS(142),
    [anon_sym_LBRACE] = ACTIONS(52),
    [sym_integer] = ACTIONS(70),
    [sym_string] = ACTIONS(74),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_constructor] = ACTIONS(70),
    [aux_sym_module_token1] = ACTIONS(58),
  },
  [STATE(16)] = {
    [sym__expr] = STATE(2),
    [sym_call] = STATE(2),
    [sym_list] = STATE(2),
    [sym_tuple] = STATE(2),
    [sym_bool] = STATE(2),
    [sym_module] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(70),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_LBRACE] = ACTIONS(52),
    [anon_sym_RBRACE] = ACTIONS(144),
    [sym_integer] = ACTIONS(70),
    [sym_string] = ACTIONS(74),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_constructor] = ACTIONS(70),
    [aux_sym_module_token1] = ACTIONS(58),
  },
  [STATE(17)] = {
    [sym__expr] = STATE(8),
    [sym_call] = STATE(8),
    [sym_list] = STATE(8),
    [sym_tuple] = STATE(8),
    [sym_bool] = STATE(8),
    [sym_module] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym_symbol] = ACTIONS(146),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_LBRACE] = ACTIONS(52),
    [anon_sym_RBRACE] = ACTIONS(148),
    [sym_integer] = ACTIONS(146),
    [sym_string] = ACTIONS(150),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_constructor] = ACTIONS(146),
    [aux_sym_module_token1] = ACTIONS(58),
  },
  [STATE(18)] = {
    [sym__expr] = STATE(6),
    [sym_call] = STATE(6),
    [sym_list] = STATE(6),
    [sym_tuple] = STATE(6),
    [sym_bool] = STATE(6),
    [sym_module] = STATE(6),
    [sym_symbol] = ACTIONS(152),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_LBRACE] = ACTIONS(52),
    [sym_integer] = ACTIONS(152),
    [sym_string] = ACTIONS(154),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_constructor] = ACTIONS(152),
    [aux_sym_module_token1] = ACTIONS(58),
  },
  [STATE(19)] = {
    [sym__expr] = STATE(3),
    [sym_call] = STATE(3),
    [sym_list] = STATE(3),
    [sym_tuple] = STATE(3),
    [sym_bool] = STATE(3),
    [sym_module] = STATE(3),
    [sym_symbol] = ACTIONS(156),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_LBRACE] = ACTIONS(52),
    [sym_integer] = ACTIONS(156),
    [sym_string] = ACTIONS(158),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_constructor] = ACTIONS(156),
    [aux_sym_module_token1] = ACTIONS(58),
  },
  [STATE(20)] = {
    [sym_symbol] = ACTIONS(160),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(162),
    [anon_sym_RPAREN] = ACTIONS(162),
    [anon_sym_LBRACK] = ACTIONS(162),
    [anon_sym_RBRACK] = ACTIONS(162),
    [anon_sym_LBRACE] = ACTIONS(162),
    [anon_sym_RBRACE] = ACTIONS(162),
    [sym_integer] = ACTIONS(160),
    [sym_string] = ACTIONS(162),
    [anon_sym_true] = ACTIONS(160),
    [anon_sym_false] = ACTIONS(160),
    [sym_constructor] = ACTIONS(160),
    [aux_sym_module_token1] = ACTIONS(162),
  },
  [STATE(21)] = {
    [sym_symbol] = ACTIONS(164),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(166),
    [anon_sym_RPAREN] = ACTIONS(166),
    [anon_sym_LBRACK] = ACTIONS(166),
    [anon_sym_RBRACK] = ACTIONS(166),
    [anon_sym_LBRACE] = ACTIONS(166),
    [anon_sym_RBRACE] = ACTIONS(166),
    [sym_integer] = ACTIONS(164),
    [sym_string] = ACTIONS(166),
    [anon_sym_true] = ACTIONS(164),
    [anon_sym_false] = ACTIONS(164),
    [sym_constructor] = ACTIONS(164),
    [aux_sym_module_token1] = ACTIONS(166),
  },
  [STATE(22)] = {
    [sym_symbol] = ACTIONS(168),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(170),
    [anon_sym_RPAREN] = ACTIONS(170),
    [anon_sym_LBRACK] = ACTIONS(170),
    [anon_sym_RBRACK] = ACTIONS(170),
    [anon_sym_LBRACE] = ACTIONS(170),
    [anon_sym_RBRACE] = ACTIONS(170),
    [sym_integer] = ACTIONS(168),
    [sym_string] = ACTIONS(170),
    [anon_sym_true] = ACTIONS(168),
    [anon_sym_false] = ACTIONS(168),
    [sym_constructor] = ACTIONS(168),
    [aux_sym_module_token1] = ACTIONS(170),
  },
  [STATE(23)] = {
    [sym_symbol] = ACTIONS(172),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(174),
    [anon_sym_RPAREN] = ACTIONS(174),
    [anon_sym_LBRACK] = ACTIONS(174),
    [anon_sym_RBRACK] = ACTIONS(174),
    [anon_sym_LBRACE] = ACTIONS(174),
    [anon_sym_RBRACE] = ACTIONS(174),
    [sym_integer] = ACTIONS(172),
    [sym_string] = ACTIONS(174),
    [anon_sym_true] = ACTIONS(172),
    [anon_sym_false] = ACTIONS(172),
    [sym_constructor] = ACTIONS(172),
    [aux_sym_module_token1] = ACTIONS(174),
  },
  [STATE(24)] = {
    [sym_symbol] = ACTIONS(176),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(178),
    [anon_sym_RPAREN] = ACTIONS(178),
    [anon_sym_LBRACK] = ACTIONS(178),
    [anon_sym_RBRACK] = ACTIONS(178),
    [anon_sym_LBRACE] = ACTIONS(178),
    [anon_sym_RBRACE] = ACTIONS(178),
    [sym_integer] = ACTIONS(176),
    [sym_string] = ACTIONS(178),
    [anon_sym_true] = ACTIONS(176),
    [anon_sym_false] = ACTIONS(176),
    [sym_constructor] = ACTIONS(176),
    [aux_sym_module_token1] = ACTIONS(178),
  },
  [STATE(25)] = {
    [sym_symbol] = ACTIONS(180),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(182),
    [anon_sym_RPAREN] = ACTIONS(182),
    [anon_sym_LBRACK] = ACTIONS(182),
    [anon_sym_RBRACK] = ACTIONS(182),
    [anon_sym_LBRACE] = ACTIONS(182),
    [anon_sym_RBRACE] = ACTIONS(182),
    [sym_integer] = ACTIONS(180),
    [sym_string] = ACTIONS(182),
    [anon_sym_true] = ACTIONS(180),
    [anon_sym_false] = ACTIONS(180),
    [sym_constructor] = ACTIONS(180),
    [aux_sym_module_token1] = ACTIONS(182),
  },
  [STATE(26)] = {
    [sym_symbol] = ACTIONS(184),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(186),
    [anon_sym_RPAREN] = ACTIONS(186),
    [anon_sym_LBRACK] = ACTIONS(186),
    [anon_sym_RBRACK] = ACTIONS(186),
    [anon_sym_LBRACE] = ACTIONS(186),
    [anon_sym_RBRACE] = ACTIONS(186),
    [sym_integer] = ACTIONS(184),
    [sym_string] = ACTIONS(186),
    [anon_sym_true] = ACTIONS(184),
    [anon_sym_false] = ACTIONS(184),
    [sym_constructor] = ACTIONS(184),
    [aux_sym_module_token1] = ACTIONS(186),
  },
  [STATE(27)] = {
    [sym_symbol] = ACTIONS(188),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(190),
    [anon_sym_RPAREN] = ACTIONS(190),
    [anon_sym_LBRACK] = ACTIONS(190),
    [anon_sym_RBRACK] = ACTIONS(190),
    [anon_sym_LBRACE] = ACTIONS(190),
    [anon_sym_RBRACE] = ACTIONS(190),
    [sym_integer] = ACTIONS(188),
    [sym_string] = ACTIONS(190),
    [anon_sym_true] = ACTIONS(188),
    [anon_sym_false] = ACTIONS(188),
    [sym_constructor] = ACTIONS(188),
    [aux_sym_module_token1] = ACTIONS(190),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 5,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_constructor,
      sym_symbol,
    ACTIONS(162), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      aux_sym_module_token1,
  [19] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 5,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_constructor,
      sym_symbol,
    ACTIONS(190), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      aux_sym_module_token1,
  [38] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 5,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_constructor,
      sym_symbol,
    ACTIONS(186), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      aux_sym_module_token1,
  [57] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 5,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_constructor,
      sym_symbol,
    ACTIONS(182), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      aux_sym_module_token1,
  [76] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 5,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_constructor,
      sym_symbol,
    ACTIONS(166), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      aux_sym_module_token1,
  [95] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 5,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_constructor,
      sym_symbol,
    ACTIONS(194), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      aux_sym_module_token1,
  [114] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 5,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_constructor,
      sym_symbol,
    ACTIONS(170), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      aux_sym_module_token1,
  [133] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 5,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_constructor,
      sym_symbol,
    ACTIONS(174), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      aux_sym_module_token1,
  [152] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 5,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_constructor,
      sym_symbol,
    ACTIONS(178), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_string,
      aux_sym_module_token1,
  [171] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_LPAREN,
    STATE(22), 1,
      sym_call,
  [181] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    STATE(34), 1,
      sym_call,
  [191] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(28)] = 0,
  [SMALL_STATE(29)] = 19,
  [SMALL_STATE(30)] = 38,
  [SMALL_STATE(31)] = 57,
  [SMALL_STATE(32)] = 76,
  [SMALL_STATE(33)] = 95,
  [SMALL_STATE(34)] = 114,
  [SMALL_STATE(35)] = 133,
  [SMALL_STATE(36)] = 152,
  [SMALL_STATE(37)] = 171,
  [SMALL_STATE(38)] = 181,
  [SMALL_STATE(39)] = 191,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_call_repeat1, 2, 0, 4), SHIFT_REPEAT(33),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 4), SHIFT_REPEAT(19),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 4),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 4), SHIFT_REPEAT(12),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 4), SHIFT_REPEAT(13),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 4), SHIFT_REPEAT(33),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_call_repeat1, 2, 0, 4), SHIFT_REPEAT(20),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 4), SHIFT_REPEAT(37),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 2, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, 0, 1),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 1),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 3, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 3, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4, 0, 3),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 3),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_call_repeat1, 1, 0, 2),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 1, 0, 2),
  [196] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tbd(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_symbol,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tbd",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
